language: node_js
notifications:
  email: false
node_js:
  - '8'
services:
  - docker
before_script:
  - ./scripts/arangodb/start.sh
script:
  - npm run test:ci
after_success:
  - npm run coveralls
  - npm run build
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
